# Generated by Django 2.2.28 on 2023-11-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255, verbose_name='comment')),
                ('label', models.IntegerField(verbose_name='label')),
                ('datetime', models.DateTimeField(verbose_name='datetime')),
            ],
        ),
    ]
